name: CI E2E

on:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: e2e
        working-directory: ui
        run: |
          docker-compose -d -f cypress-dc-local.yml up
          npm install
          npm run cy:run-dc-local
